# Generated by Django 3.1.7 on 2021-05-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210302_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='pay_range',
        ),
    ]
