# Generated by Django 3.1.7 on 2021-07-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_job_pay_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrange',
            name='currency',
            field=models.CharField(choices=[('VND', 'Việt Nam Đồng'), ('USD', 'Đô La Mỹ')], default='VND', max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='option',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], default='good', max_length=255),
        ),
        migrations.AlterField(
            model_name='reportticket',
            name='option',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], default='good', max_length=255),
        ),
    ]
