# Generated by Django 3.1.6 on 2021-02-23 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
