# Generated by Django 3.1.7 on 2021-02-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='skill',
            field=models.CharField(choices=[('Boob', 'No Skill')], default='Boob', max_length=255),
        ),
    ]
