# Generated by Django 3.1.7 on 2021-03-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210302_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
    ]
