# Generated by Django 3.1.7 on 2021-05-05 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210411_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number can only contain numbers', regex='^[0-9]*$')]),
        ),
    ]
