# Generated by Django 3.1.7 on 2021-05-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210507_1341'),
        ('user', '0018_auto_20210512_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(related_name='user_skills', through='user.UserSkill', to='common.Category'),
        ),
    ]
