# Generated by Django 3.1.7 on 2021-05-16 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210507_1341'),
        ('user', '0020_auto_20210516_0029'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'skill')},
        ),
    ]
