# Generated by Django 3.1.7 on 2021-06-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210507_1341'),
        ('user', '0021_auto_20210516_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='user_skills', through='user.UserSkill', to='common.Category'),
        ),
    ]
