# Generated by Django 3.1.7 on 2021-07-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_merge_20210616_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='number_pay',
            new_name='number_of_payments_paid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='number_rating',
            new_name='number_of_ratings',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='total_pay',
            new_name='total_paid_amount',
        ),
        migrations.RenameField(
            model_name='userskill',
            old_name='number_rating',
            new_name='number_of_ratings',
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='headline',
            field=models.TextField(blank=True),
        ),
    ]
