# Generated by Django 3.1.6 on 2021-02-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='N/A', max_length=255, unique=True),
        ),
    ]
