# Generated by Django 3.1.7 on 2021-05-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_tag_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
    ]
